defaults:
  - default.yaml

_target_: salad.models.phase2.Phase2Model
network:
  _target_: salad.model_components.network.CondDiffNetwork
  input_dim: 256
  residual: true
  context_dim: 10 # condition dim.
  context_embedding_dim: 256
  embedding_dim: 256
  encoder_use_time: false
  encoder_type: transformer
  decoder_type: transformer_encoder # we don't use cross attention.
  enc_num_layers: 6
  dec_num_layers: 6
  use_timestep_embedder: true
  timestep_embedder_dim: 128


dataset_kwargs:
  data_keys: ["s_j_affine", "g_js_affine"]
